# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3211b7a4916aff4700f324cbf6af8bc1f3591bb9965caf479bd8e7999b65120b8635f2fa4c6a129843d25627e140a943fd4af0b7a7978abd5ef826302b90f294

test:
  secret_key_base: d967b026b2cc1faf2dff1663ac0db6b434a40202eb177ef8d69681e817e0304d92cd16d800d8df6bb17469f8a80ced670e6ae42ffc03d94972ecbe8693a3c5e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
